name: portfolio
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0
  dio_http: ^5.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
